clear all;
% a)
figure(1);
x=[1,1,1,1,1];
dtx=0:4;
subplot(221);
stem(dtx,x);
xlabel('n'), ylabel('x');
h=[1,1,1,1,1];
dth=-2:2;
subplot(222);
stem(dth,h);
xlabel('n'), ylabel('h');
z=conv(x,h);
dtz=-2:6;
subplot(223);
stem(dtz,z);
xlabel('n'), ylabel('z');
% b)
figure(2);
x=[0.5,0.5,0.5];
dtx=0:2;
subplot(221);
stem(dtx,x);
xlabel('n'), ylabel('x');
h=[3,2,1];
dth=0:2;
subplot(222);
stem(dth,h);
xlabel('n'), ylabel('h');
z=conv(x,h)
dtz=0:4;
subplot(223);
stem(dtz,z);
xlabel('n'), ylabel('z');
% c)
figure (3);
n=-5:5;
x=5-n;
dtx=-5:5;
subplot(221);
stem(dtx,x);
xlabel('n'), ylabel('x');
h=ones(1,11);
dth=-5:5;
subplot(222);
stem(dth,h);
xlabel('n'), ylabel('h');
z=conv(x,h);
dtz=-10:10;
subplot(223);
stem(dtz,z);
xlabel('n'), ylabel('z');
% d)
figure(4);
x=ones(1,21);
dtx=0:20;
subplot(221);
stem(dtx,x);
xlabel('n'), ylabel('x');
n=-10:10;
h=(0.5).^(n-1);
dth=-10:10;
subplot(222);
stem(dth,h);
xlabel('n'), ylabel('h');
z=conv(x,h);
dtz=-10:30;
subplot(223);
stem(dtz,z);
xlabel('n'), ylabel('z');
% e)
figure (5);
n=-2:1;
x=1-1.3*exp(n/5);
dtx=-2:1;
subplot(221);
stem(dtx,x);
xlabel('n'), ylabel('x');
p=0:4;
h=exp(-0.7*p);
dth=0:4;
subplot(222);
stem(dth,h);
xlabel('n'), ylabel('h');
z=conv(x,h);
dtz=-2:5;
subplot(223);
stem(dtz,z);
xlabel('n'), ylabel('z');
